### PR TITLE
Added docu for line hooks in reledpar

### PR DESCRIPTION
**Pull request by baem2**
So far these are only documented in the code docu, not in the manual part

### CODE REVIEW

**Comment by maieul** [comment]
hum it is redundant with c3ff4be, isn't it ?

**Comment by baem2** [comment]
Didn't see that, indeed!

**Comment by maieul** [comment]
in general, I do the commit related to the feature in the concerned branch. I never do commit directly in master, except for little typo.

**Comment by baem2** [comment]
Yup, will try to do better next time!

**Pull request closed without merging**
