### PR TITLE
Mark's English corrections

### PR DESCRIPTION
**Pull request by bishopcranmer**
- Misc. corrections for minor English typographical errors
- Change "not column" or "no column" to "single column(s)"

### CODE REVIEW

**Comment by maieul** [comment]
thanks

**Comment by maieul** [comment]
what was you comparaison point ? did you do from https://huit.re/S9WeBALw ? what rebecca should do in Friday? If yes, I will tell her that all is ok.

**Comment by bishopcranmer** [comment]
Yes, I used your the “green lines” at https://huit.re/S9WeBALw <https://huit.re/S9WeBALw> and then used a fork of your master under my user name and compared them side by side. Was that correct?

M

**Comment by maieul** [comment]
yes it was !
Was quite easy today because you have worked on master branch. Habitually, I work with an other one.

**Pull request merged**
