### PR TITLE
Issue617

### PR DESCRIPTION
**Pull request by tweh**
My suggested fix for issue #617.

### CODE REVIEW

**Comment by maieul** [comment]
actually, I am finishing to re-read my thesis. So I don't wan't to touch reledpar before the final compilation.

I will look on it next week-end. Remember me if I don't

**Comment by maieul** [comment]
I have just look on you'r branch and it look good… but by principle, I won't touch.

**Comment by tweh** [comment]
Sure :-) No problem! I just found this issue, but I don’t need it to be fixed at the moment (I guess most users set the same sep before and after an never note this bug) …

Best for your thesis!

**Comment by maieul** [comment]
I have integrated it. Thanks.

Please next time, call your example file issueXXX.tex

**Comment by tweh** [comment]
Thanks for including :-)

**Pull request merged**
