### PR TITLE
Marks experiment

### PR DESCRIPTION
**Pull request by bishopcranmer**
M. Rouquette: I’m trying to learn how to use Github’s desktop application. The slight changes I made are accurate, but there is nothing really important. It’s more just to see if I’m getting this
process right.

### CODE REVIEW

**Comment by bishopcranmer** [comment]
Sure. Done.

M

**Comment by maieul** [comment]
you must to push this commit on github. I don't see it.

**Comment by bishopcranmer** [comment]
How about now?

M

**Comment by maieul** [comment]
no. You add the commit in a new branch, and not in the same branch. Look at https://github.com/bishopcranmer/ledmac/network. You have two branch from master, while you should have only one with two commit.

**Comment by maieul** [comment]
hi, some feedback?

**Pull request closed without merging**
