### PR TITLE
Fix for #389

### PR DESCRIPTION
**Pull request by tweh**
Hope now it works …

### CODE REVIEW

**Comment by maieul** [comment]
yes, it works, but your historic is not very good, you have merge commit not needed (04920b4aead1f0baf0245b5dfa6fccbeaba4dc36  should have been done by a ff, or not done at all, 8d745384f085886f5af4e88c6c0e21bb193e3284 should not exist). 

Indeed, thanks for the correction

**Comment by maieul** [comment]
Yes, it was working, but your historic was with bad commit:
- 04920b4aead1f0baf0245b5dfa6fccbeaba4dc36 should be done by a ff
- 8d745384f085886f5af4e88c6c0e21bb193e3284 should not exist
- df42e833fb3ed3b910f01c08d70769954437702f should not exist (you should have pull request directly from tweh/issue389 to maieul/2.1.3-2.2.1).

As it is a short case, that does not matter. But for feature ;-)

in any case, thanks for your quite debug. You are ready to find the nopbinverse good algorithm :-)

**Comment by tweh** [comment]
I'll take a look at it after I read a Git tutorial …

btw. can I delete my fork (and create a new one to clean my errors) without any harm on your repo?

> You are ready to find the nopbinverse good algorithm :-)
We'll see but for now I guess I'll only correct simple stuff like typos ;-)
—

Tobi W_


Tobias Weh
Spindelstraße 25
49080 Osnabrück

+49 (0)541 40757837

mail@tobiw.de
http://tobiw.de

**Comment by maieul** [comment]
> 
> btw. can I delete my fork (and create a new one to clean my errors) without any harm on your repo?
you can do it of course ;-) but as I have integrated one time, I won't integrate it a second time again.

But you should not do it, just clean it and synchronize it with my repos (https://help.github.com/articles/syncing-a-fork/)

**Comment by tweh** [comment]
Hi, I guess I slowly understand how `git` works, but it’s at least as complex as finding a `nopbinverse` algorithm ;-) so I hope you don’t mind some more stupid questions :-)

> - 04920b4 should be done by a ff

What does _ff_ mean?


> - df42e83 should not exist (you should have pull request directly from tweh/issue389 to maieul/2.1.3-2.2.1).

If I had done it this way, can I delete my branch after the request or do I have to wait until you included it in your repo?

> But you should not do it, just clean it and synchronize it with my repos 
Done … I hope … :-)

PS: You may want to change the repos description (“package eledmac for latex http://www.ctan.org/tex-archive/macros/latex/contrib/eledmac”) to reledmac instead of ledmac.

**Comment by maieul** [comment]
> Hi, I guess I slowly understand how git works, but it�s at least as complex as finding a nopbinverse algorithm ;-) so I hope you don�t mind some more stupid questions :-)
> 
> 	� 04920b4 should be done by a ff
> What does ff mean?
> 
fast forward. http://ariya.ofilabs.com/2013/09/fast-forward-git-merge.html
> 	� df42e83 should not exist (you should have pull request directly from tweh/issue389 to maieul/2.1.3-2.2.1).
> If I had done it this way, can I delete my branch after the request or do I have to wait until you included it in your repo?
> 
don't know. But i think you should keept it.
> But you should not do it, just clean it and synchronize it with my repos 
> Done � I hope � :-)
> 
> PS: You may want to change the repos description (�package eledmac for latex http://www.ctan.org/tex-archive/macros/latex/contrib/eledmac�) to reledmac instead of ledmac.

done

**Pull request merged**
